In [1]:
'''Broadcasting in NumPy:

Broadcasting is a technique that allows NumPy to perform 
operations on arrays with different shapes.

NumPy automatically expands the smaller array to match 
the shape of the larger array without actually copying data.'''

# with 1D array

import numpy as np

arr = np.array([10,20,30])

print(arr +10)

[20 30 40]


In [4]:
# with 2D array

import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [9,5,7]])

arr2 = np.array([10,20,30])

new = arr1 + arr2
print(new)

[[11 22 33]
 [14 25 36]
 [19 25 37]]
