In [1]:
# For 1D array

import numpy as np 
arr = np.array([10,20,30,40,50])

new_arr = np.delete(arr, 2)
print(new_arr)

[10 20 40 50]


In [7]:
# For 2D array

import numpy as np
arr = np.array([[10,20,30],
                [40,50,60]])

print(arr)
print("\n")
new_arr = np.delete(arr, 1, axis= 0)
# Row wise delete
print(new_arr)

# Calumn wise delete
new_arr2 = np.delete(arr, 0, axis = 1)
print("\n")
print(new_arr2)


[[10 20 30]
 [40 50 60]]


[[10 20 30]]


[[20 30]
 [50 60]]
