In [ ]:
#Row wise
import numpy as np
arr = np.array([[10,20],
                [30,40],
                [50,60]])

print(arr)
print("\n")
new_arr = np.insert(arr, 1, [1,2], axis= 0)
print(new_arr)
print("\n")

[[10 20]
 [30 40]
 [50 60]]


[[10 20]
 [ 1  2]
 [30 40]
 [50 60]]




In [ ]:
# Calumn wise
import numpy as np

arr = np.array([[1,2],
                [3,4]])

print(arr)
print("\n")
new_arr = np.insert(arr, 1, [0,9], axis= 1)
print(new_arr)

[[1 2]
 [3 4]]


[[1 0 2]
 [3 9 4]]
