In [3]:
'''Stacking in NumPy:

Stacking means joining two or more arrays together 
along a specific axis to create a new array.

It is used to combine multiple arrays into one array.'''

# 1. vstack()   -> row wise 

import numpy as np
arr1 = np.array([[1,2,3],
                [9,0,9]])
arr2 = np.array([[4,5,6],
                [9,9,9]])

new = np.vstack((arr1,arr2))

print(new)



[[1 2 3]
 [9 0 9]
 [4 5 6]
 [9 9 9]]


In [4]:
# hstack    -> calumn wise

import numpy as np

arr1 = np.array([[1,2,3],
                [9,0,9]])
arr2 = np.array([[4,5,6],
                [9,9,9]])

new = np.hstack((arr1,arr2))

print(new)

[[1 2 3 4 5 6]
 [9 0 9 9 9 9]]
